// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl01A3-M32ZSCkOYEaUp7EQjb8qBniXog',
    appId: '1:412919918176:web:1962febf7f359e09a81d05',
    messagingSenderId: '412919918176',
    projectId: 'last-minute-57857',
    authDomain: 'last-minute-57857.firebaseapp.com',
    storageBucket: 'last-minute-57857.appspot.com',
    measurementId: 'G-HHEKHFR310',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-vV-C4zXmszu0OSoE1yNccTzyVH8o50',
    appId: '1:412919918176:android:9c3356d03a8cc58aa81d05',
    messagingSenderId: '412919918176',
    projectId: 'last-minute-57857',
    storageBucket: 'last-minute-57857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAudU6MID2cM_aAS7wMX7lTmBsQUGRkNs',
    appId: '1:412919918176:ios:062f082996fde5eaa81d05',
    messagingSenderId: '412919918176',
    projectId: 'last-minute-57857',
    storageBucket: 'last-minute-57857.appspot.com',
    androidClientId: '412919918176-3b8sdlvj676qkno6udhl2vnuajp2ohhl.apps.googleusercontent.com',
    iosClientId: '412919918176-p90lhr9b2g02mgs8jo7upfegjm1se5ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.lastMinuteAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAudU6MID2cM_aAS7wMX7lTmBsQUGRkNs',
    appId: '1:412919918176:ios:062f082996fde5eaa81d05',
    messagingSenderId: '412919918176',
    projectId: 'last-minute-57857',
    storageBucket: 'last-minute-57857.appspot.com',
    androidClientId: '412919918176-3b8sdlvj676qkno6udhl2vnuajp2ohhl.apps.googleusercontent.com',
    iosClientId: '412919918176-p90lhr9b2g02mgs8jo7upfegjm1se5ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.lastMinuteAdminPanel',
  );
}
